name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

# TODO: if job names don't include dir, set the job name maually
# TODO: add e2e test ci
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['ssoclient', 'ssoproxy'] }
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: '^1.21'
        check-latest: true
        cache: true
    
    - name: golangci-lint ${{ matrix.dir }}
      uses: golangci/golangci-lint-action@v4.0.0
      with:
        working-directory: ${{ matrix.dir }}
        version: latest
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['ssoclient', 'ssoproxy'] }
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # must be set to be able to push

    - uses: actions/setup-go@v5
      with:
        # TODO: consider using go-version-file with matrix if go is initialized twice (for each dir)
        go-version: '^1.21'
        check-latest: true
        cache: true

    - name: install gotestfmt
      uses: GoTestTools/gotestfmt-action@v2
      with:
        version: v2.5.0

    - name: test
      working-directory: ${{ matrix.dir }}
      run: |
        go test -v -json ./... -covermode=count -coverprofile=coverage-${{ matrix.dir }}.out 2>&1 | tee /tmp/gotest.log | gotestfmt
        go tool cover -func=coverage-${{ matrix.dir }}.out -o=coverage-${{ matrix.dir }}.out
    
    - name: update badge
      uses: tj-actions/coverage-badge-go@v2
      with:
        filename: coverage-${{ matrix.dir }}.out
        text: ${{ matrix.dir }}

    - name: verify badge changed
      uses: tj-actions/verify-changed-files@v16
      id: verify-changed-files
      with:
        files: README.md

    - name: commit badge
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "chore: Updated coverage badge."

    - name: push badge
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ github.token }}
        branch: ${{ github.head_ref }}
