name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        dir: ['ssoclient', 'ssoproxy']
      fail-fast: false
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version-file: ${{ matrix.dir }}/go.mod
        cache: false
    
    - name: golangci-lint ${{ matrix.dir }}
      uses: golangci/golangci-lint-action@v4.0.0
      with:
        working-directory: ${{ matrix.dir }}
        version: latest
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        dir: ['ssoclient', 'ssoproxy', 'e2e-tests']
      fail-fast: false
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version-file: ${{ matrix.dir }}/go.mod
        cache: false

    - name: install gotestfmt
      uses: GoTestTools/gotestfmt-action@v2
      with:
        version: v2.5.0

    - name: test
      working-directory: ${{ matrix.dir }}
      run: |
        go test -timeout 10m -v -json ./... -covermode=count -coverprofile=${{ matrix.dir }}-coverage.out 2>&1 | gotestfmt
        go tool cover -func=${{ matrix.dir }}-coverage.out -o=../${{ matrix.dir }}-coverage.out

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.dir }}-coverage
        path: ${{ matrix.dir }}-coverage.out
        retention-days: 1
        if-no-files-found: error

  update-coverage-badges:
    name: update coverage badges
    if: github.ref == 'refs/heads/main'
    concurrency: # if there is another push to main, cancel in-progress CI
      group: ${{ github.ref }}
      cancel-in-progress: true
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # must be set to be able to push

      - name: load test output
        uses: actions/download-artifact@v4
        with:
          pattern: '*-coverage'
          merge-multiple: true

      - name: update badges
        run: |
          TEMP_DIR=$(mktemp -d)
          curl -sf https://gobinaries.com/github.com/AlexBeauchemin/gobadge@v0.3.0 | PREFIX=$TEMP_DIR sh
          $TEMP_DIR/gobadge -filename=${{ github.workspace }}/ssoclient-coverage.out -text=ssoclient/coverage
          $TEMP_DIR/gobadge -filename=${{ github.workspace }}/ssoproxy-coverage.out -text=ssoproxy/coverage
          rm -rf $TEMP_DIR

      - name: verify badges changed
        uses: tj-actions/verify-changed-files@v19
        id: verify-changed-files
        with:
          files: README.md

      - name: commit badges
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "chore: Updated coverage badges"

      - name: push badges
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: ${{ github.head_ref }}